occupations = [
[".NET Developer / Engineer","414"],
["Academic / Guidance Counselor","37019"],
["Account Executive & Publisher","46"],
["Account Executive (General)","598"],
["Account Manager","1969"],
["Account Representative","1203"],
["Account Supervisor","37"],
["Accountant (General)","10415"],
["Accounting Analyst","2852"],
["Accounting Clerk","12222"],
["Accounting Manager","2347"],
["Accounting Specialist","3758"],
["Accounting Supervisor","568"],
["Accounts Payable / Receivable Manager","819"],
["Accounts Receivable / Payable Clerk","1976"],
["Accounts Receivable / Payable Specialist","1942"],
["Actor","826"],
["Actuary","127"],
["Acupuncturist","191"],
["Additive Manufacturing Engineer","8"],
["Administrative Clerk / Coordinator","28228"],
["Administrative Manager","21825"],
["Administrative Sales Assistant","39"],
["Administrative Supervisor","4176"],
["Administrator, Higher Education","61409"],
["Admissions Administrator","21350"],
["Admissions Director","16921"],
["Adult Basic Education / Literacy Instructor","1908"],
["Advanced Manufacturing Engineer","10"],
["Advertising / Promotions Manager","795"],
["Advertising Account Executive","23"],
["Advertising Executive and Publisher","2"],
["Advertising Sales Executive","58"],
["Advertising Sales Representative","246"],
["Advertising and Marketing Coordinator","6"],
["Advertising and Marketing Sales Assistant","106"],
["Aerospace Engineer","992"],
["Aerospace Engineering Manager","25"],
["Agricultural Lender","1"],
["Agriculture & Food Engineering Manager","2"],
["Air Traffic Controller","229"],
["Aircraft / A & P Mechanic","335"],
["Alarm / Security System Technician","376"],
["Alternative Energy Manager","40"],
["Alumni Relations Manager","4999"],
["Analytical Chemist","804"],
["Analytics Product Manager","12"],
["Android Developer / Engineer","48"],
["Anesthesia Technician","1931"],
["Animal Control Officer","53"],
["Appliance Retail Sales Associate","13"],
["Application Analyst","2233"],
["Application Developer / Engineer","7773"],
["Application Manager","316"],
["Application Support Engineer / Analyst","4014"],
["Arborist / Faller","112"],
["Archeologist","205"],
["Architect","1839"],
["Archivist","1873"],
["Armed Security Officer","45"],
["Art / Music / Recreational Therapist","877"],
["Art Director","1187"],
["Art Teacher","299"],
["Artist / Illustrator","926"],
["Assay Development Scientist","5"],
["Assistant Branch Manager","45"],
["Assistant Controller","511"],
["Assistant Director of Nursing","514"],
["Assistant General Manager","611"],
["Assistant Project Manager","660"],
["Assistant Property Manager","211"],
["Assistant Retail Store Manager","608"],
["Assistant Sales Manager","138"],
["Assistant School Principal","351"],
["Assistant Web Designer","84"],
["Associate Dean, Higher Education","6425"],
["Athletic Trainer","7269"],
["Attorney","4863"],
["Audio / Visual Technician","2652"],
["Audio Visual Engineer","63"],
["Audiologist","868"],
["Audit Manager","317"],
["Auditor (General)","1563"],
["Auto Body Technician","517"],
["Auto Damage Appraiser","15"],
["Auto Parts Delivery Driver","6"],
["Automation Engineer","60"],
["Automation Technician","118"],
["Automotive Customer Service Representative","54"],
["Automotive Electronics Installer","3"],
["Automotive Engineer","11"],
["Automotive General Manager","58"],
["Automotive Glass Installer","6"],
["Automotive Office Manager","1"],
["Automotive Process Engineer","1"],
["Automotive Service Manager","271"],
["Automotive Service Technician / Mechanic","3329"],
["Automotive Title Clerk","1"],
["Aviation / Aircraft Inspector","6"],
["Avionics Technician","306"],
["Back End Developer / Engineer","52"],
["Bailiff","9"],
["Baker","1127"],
["Banking Branch Manager","146"],
["Banking Manager","10"],
["Barber / Hair Stylist / Cosmetologist","393"],
["Barista","486"],
["Bartender","586"],
["Behavior Analyst","242"],
["Bell Person / Baggage Attendant","168"],
["Big Data Architect","10"],
["Bike Technician","35"],
["Bilingual / ESL / Foreign Language Teacher","5208"],
["Billing Analyst","234"],
["Billing Clerk","1230"],
["Billing Specialist","1148"],
["Billing Supervisor","162"],
["Binding Machine Operator","17"],
["Biochemist","456"],
["Bioinformatician","1217"],
["Bioinformatics Engineer","12"],
["Bioinstrumentation Engineer","28"],
["Biological Technician","7352"],
["Biologist","957"],
["Biology Laboratory Technician","3030"],
["Biology Research Scientist","1096"],
["Biomechanical Engineer","21"],
["Biomechatronics Engineer","6"],
["Biomedical Electronics Engineer","9"],
["Biomedical Electronics Technician","156"],
["Biomedical Engineer","238"],
["Biomedical Engineering Manager","98"],
["Biomedical Equipment Technician","1631"],
["Biomedical Imaging Scientist","29"],
["Biomedical Scientist","121"],
["Biomedical Systems Engineer","30"],
["Bionanotechnologist","5"],
["Biostatistician","2099"],
["Biostatistics Manager / Director","169"],
["Blood Bank Technologist","314"],
["Boilermaker","31"],
["Bookkeeper","562"],
["Bookseller","44"],
["Brand Ambassador","576"],
["Brand Manager","360"],
["Brand Marketing Specialist","152"],
["Brick / Stone Mason","260"],
["Broadband Technician","101"],
["Broadcast Technician","1188"],
["Brokerage Clerk","12"],
["Budget Analyst","3637"],
["Build and Release Engineer","55"],
["Building Engineer","45"],
["Building and General Maintenance Technician ","12713"],
["Bus Driver","1723"],
["Business / Management Consultant","1232"],
["Business / Systems Analyst","5691"],
["Business Analysis Manager","48"],
["Business Analyst (General)","6385"],
["Business Banker","4"],
["Business Continuity Planner / Analyst","441"],
["Business Development Manager","404"],
["Business Development Specialist","460"],
["Business Intelligence Analyst","3996"],
["Business Intelligence Developer / Architect","1308"],
["Business Office Manager","880"],
["Business Process Analyst","650"],
["Business to Business (B2B) Account Executive","28"],
["Business to Business (B2B) Sales Representative","168"],
["Busser / Banquet Worker / Cafeteria Attendant","731"],
["Butcher / Meat Cutter","72"],
["Buyer (General)","1768"],
["C / C++ Developer / Engineer","98"],
["C# Developer / Engineer","94"],
["CAD Designer / Drafter","626"],
["CMS Developer","342"],
["CNC Operator","177"],
["CNC Programmer","64"],
["CNC and Machining Manufacturing Engineer","39"],
["Cabinetmaker","112"],
["Cable Technician / Installer","136"],
["Cage Cashier","5"],
["Calibration Technician","78"],
["Call Center Manager","470"],
["Call Center Representative","2207"],
["Call Center Sales Representative","55"],
["Campus Director","2917"],
["Campus Recruiter","617"],
["Campus Security Officer","9035"],
["Canvasser","11"],
["Carbon Reduction Engineer","1"],
["Cardiology Registered Nurse","2801"],
["Cardiovascular Research Scientist","145"],
["Cardiovascular Technician / Technologist","5045"],
["Care Coordinator","1676"],
["Career Counselor","7727"],
["Caregiver / Personal Care Aide","2069"],
["Cargo Coordinator / Freight Forwarder","122"],
["Carpenter","2326"],
["Carpet Installer","34"],
["Case Worker","242"],
["Cashier","4647"],
["Cashier & Checker","3"],
["Cashier & Clerk","89"],
["Cashier & Cook","4"],
["Cashier & Host","2"],
["Casino & Gaming Security Officer","7"],
["Casino Dealer","11"],
["Catering Sales Manager","75"],
["Cell Biologist","967"],
["Cellular, Tissue, and Genetic Engineer","28"],
["Channel Sales Engineer","1"],
["Channel Sales Manager","1"],
["Chaplain / Pastor / Priest","2854"],
["Charge Nurse","1183"],
["Chef","3219"],
["Chemical Engineer","30"],
["Chemical Engineering Manager","86"],
["Chemical Operator","100"],
["Chemical Process Engineer","29"],
["Chemical Technician","2044"],
["Chemist (General)","3749"],
["Chemistry Laboratory Supervisor","315"],
["Chief Executive Officer","3429"],
["Chief Financial Officer","1135"],
["Chief Information Officer","1893"],
["Chief Marketing Officer","172"],
["Chief Medical Officer","202"],
["Chief Nursing Officer","181"],
["Chief Technology Officer","279"],
["Chief of Staff","390"],
["Childbirth Educator","81"],
["Childcare / Preschool Director","1121"],
["Chiropractor","20"],
["Choreographer","39"],
["Cisco Engineer","84"],
["Citrix Engineer","243"],
["City / Town Administrator","6"],
["City / Town Manager","40"],
["City and Town Planner","9"],
["Civil / Architectural Designer / Drafter","109"],
["Civil Engineer","2240"],
["Civil Engineering Manager","213"],
["Civil Engineering Technician","877"],
["Claims Adjuster / Specialist","961"],
["Claims Examiner","180"],
["Claims Investigator","73"],
["Claims Processor","38"],
["Claims Representative","644"],
["Claims Supervisor","122"],
["Client Delivery Director","5"],
["Client Engagement Manager","167"],
["Client Relationship Manager","114"],
["Client Service Representative / Associate","1597"],
["Clinical Auditor / Utilization Reviewer","338"],
["Clinical Biomedical Engineer","53"],
["Clinical Case Manager","5218"],
["Clinical Coordinator","6495"],
["Clinical Data Analyst","1230"],
["Clinical Data Coordinator","432"],
["Clinical Data Developer","93"],
["Clinical Data Manager","161"],
["Clinical Data Project Manager","66"],
["Clinical Data Specialist","322"],
["Clinical Data Systems Analyst","1749"],
["Clinical Data Systems Consultant","6"],
["Clinical Data Systems Coordinator","58"],
["Clinical Data Systems Trainer","107"],
["Clinical Director","722"],
["Clinical Documentation Specialist","2157"],
["Clinical Laboratory Specialist","172"],
["Clinical Laboratory Technician","2231"],
["Clinical Nurse Educator","2692"],
["Clinical Nurse Specialist","1838"],
["Clinical Nurse Supervisor","916"],
["Clinical Nursing Manager / Director","1259"],
["Clinical Office Manager","25"],
["Clinical Pharmacist","2896"],
["Clinical Pharmacy Manager","213"],
["Clinical Practice Manager","20"],
["Clinical Project Manager","449"],
["Clinical Quality Improvement Specialist","478"],
["Clinical Quality Manager","54"],
["Clinical Research Associate","17"],
["Clinical Research Coordinator","10843"],
["Clinical Research Director","381"],
["Clinical Research Manager","611"],
["Clinical Site Coordinator","13"],
["Clinical Supervisor","1520"],
["Clinical Supervisor / Manager","9309"],
["Clinical Trial Manager","321"],
["Cloud Architect","25"],
["Cloud Product Manager","18"],
["Cloud Sales Representative","4"],
["Coach","46261"],
["Coating / Industrial Painter","48"],
["Collections Analyst","2"],
["Collections Manager","399"],
["Collections Specialist","2707"],
["College Athletic Director","2571"],
["College Professor / Instructor","869652"],
["Commercial Construction Manager","31"],
["Commercial Construction Project Manager","34"],
["Commercial Construction Superintendent","8"],
["Commodities / Manufacturing Buyer","111"],
["Communications Campaign Manager","35"],
["Communications Director","4511"],
["Communications Manager","6121"],
["Community Health Worker","386"],
["Community Planner","43"],
["Community Relations Director","159"],
["Community Relations Manager","248"],
["Compensation / Benefits Analyst","1248"],
["Compensation / Benefits Manager","1231"],
["Compensation / Benefits Specialist","3419"],
["Completions Engineer","6"],
["Compliance Auditor","334"],
["Compliance Manager","4007"],
["Compliance Officer / Analyst","5165"],
["Composer","15"],
["Compounding Pharmacist","6"],
["Computational Biologist","180"],
["Computational Chemist","71"],
["Computer Circuit Design Engineer","258"],
["Computer Operator","917"],
["Computer Programmer","5875"],
["Computer Repair Technician","1086"],
["Computer Scientist / Researcher","3538"],
["Computer Support Specialist","8335"],
["Concierge","359"],
["Concrete Finisher","75"],
["Configuration Analyst / Specialist","174"],
["Conservation Scientist / Park Ranger","583"],
["Construction / Building Inspector","568"],
["Construction Accountant","26"],
["Construction Director","690"],
["Construction Electrical Designer","8"],
["Construction Engineering Manager","104"],
["Construction Foreman","658"],
["Construction Helper / Worker","2029"],
["Construction Manager","1250"],
["Construction Office Manager","16"],
["Construction Project Manager","871"],
["Construction Safety Manager","54"],
["Construction Safety Specialist","135"],
["Construction Site Manager","21"],
["Construction Superintendent","70"],
["Consulting Sales Manager","9"],
["Consumer Safety Specialist","2"],
["Content Marketing Manager","130"],
["Content Marketing Specialist","84"],
["Contracts Administrator","2227"],
["Contracts Analyst","167"],
["Contracts Manager","712"],
["Controller (General)","2259"],
["Controls / Valve Technician","604"],
["Cook","8576"],
["Coordinate Measuring Machine (CMM) Specialist","21"],
["Copywriter","532"],
["Corporate Development Analyst / Manager","301"],
["Corporate Trainer","315"],
["Correctional Officer / Jailer","939"],
["Cost Accountant","927"],
["Cost Accounting Manager","469"],
["Costume / Wardrobe Attendant","81"],
["Counter Sales Clerk","128"],
["Courier / Messenger","776"],
["Court Security Officer","1"],
["Crane Operator","33"],
["Credit / Loan Counselor","664"],
["Credit Analyst","72"],
["Credit Manager","53"],
["Credit Officer","25"],
["Credit Specialist / Clerk","141"],
["Crime Scene / Forensic Science Technician","163"],
["Criminal Investigator","188"],
["Curator / Museum Director","2756"],
["Curriculum and Instructional Designer / Developer","17309"],
["Customer Experience Manager","17"],
["Customer Service Account Manager","12"],
["Customer Service Director","65"],
["Customer Service Manager","381"],
["Customer Service Representative (General)","9841"],
["Customer Service Supervisor","213"],
["Customer Success Manager","15"],
["Customs Broker","1"],
["Cyber Crime Analyst / Investigator","38"],
["Cyber Security Analyst","2231"],
["Cyber Security Architect","145"],
["Cyber Security Consultant","555"],
["Cyber Security Engineer","1974"],
["Cyber Security Manager / Administrator","1382"],
["Cyber Security Specialist / Technician","2261"],
["Cybersecurity Product Manager","1"],
["Cytogenetic Technologist / Cytotechnologist","1541"],
["DJ / Announcer","31"],
["Dance Teacher","567"],
["Data Analyst (Business Performance)","230"],
["Data Analyst (Finance)","137"],
["Data Analyst (General)","4590"],
["Data Analyst (Healthcare)","1205"],
["Data Analyst (Marketing)","242"],
["Data Architect","324"],
["Data Center Technician / Engineer","512"],
["Data Engineer","76"],
["Data Entry Clerk","3019"],
["Data Manager","1394"],
["Data Quality Analyst","320"],
["Data Scientist","489"],
["Data Specialist","1257"],
["Data Warehouse Developer","1346"],
["Database Administrator","5567"],
["Database Analyst / Developer","1233"],
["Database Architect","760"],
["Dean (General)","1679"],
["Dean of Academic Affairs","8034"],
["Dean of Academic Division","19507"],
["Dean of Students","3101"],
["Decision Support Analyst","485"],
["Dedicated Truck Driver","8"],
["Demand Planner","1"],
["Demand Planning Analyst","6"],
["Demand Planning Manager","11"],
["Dental Assistant","3793"],
["Dental Hygienist","1099"],
["Dental Laboratory Technician","349"],
["Dental Office Manager","9"],
["Dental Practice Manager","81"],
["Dentist / Orthodontist / Prosthodontist","1071"],
["Department Manager","477"],
["Design Engineering Manager","68"],
["Design Engineering Technician","56"],
["Detailer","202"],
["Devops Engineer","321"],
["Diabetes Educator","288"],
["Dialysis Registered Nurse","654"],
["Dialysis Technician","562"],
["Diesel Mechanic","416"],
["Dietary Aide","221"],
["Dietitian / Nutritionist","3614"],
["Digital Advertising Sales Representative","10"],
["Digital Marketing Analyst","146"],
["Digital Marketing Director","388"],
["Digital Marketing Manager","457"],
["Digital Marketing Specialist","810"],
["Director of Assisted Living","4"],
["Director of Business Development","787"],
["Director of Case Management","197"],
["Director of Compensation / Benefits","492"],
["Director of Customer Success","6"],
["Director of Engineering","2119"],
["Director of Government Affairs","73"],
["Director of Health Information Management","400"],
["Director of Human Resources","6617"],
["Director of Institutional Research","563"],
["Director of Instruction / Curriculum Specialist","2254"],
["Director of Laboratory Services","363"],
["Director of Nursing","3064"],
["Director of Operations","3836"],
["Director of Procurement / Sourcing","786"],
["Director of Product Development","46"],
["Director of Product Management","61"],
["Director of Program Management","1750"],
["Director of Project Management","1038"],
["Director of Quality Assurance","341"],
["Director of Rehabilitation","908"],
["Director of Religious Education","1210"],
["Director of Risk Management","593"],
["Director of Sales","280"],
["Director of Special Education","654"],
["Director of Student Affairs","12432"],
["Director of Surgical Services","965"],
["Director of Talent Acquisition","232"],
["Director of Training and Development","1938"],
["Director of Transportation","203"],
["Dishwasher","1474"],
["Dispatcher","5790"],
["Distribution Center Manager","65"],
["Distribution Manager","39"],
["Document Control / Management Specialist","2080"],
["Door To Door Sales Representative","55"],
["Drama Teacher","119"],
["Driller / Drill Operator","3"],
["Drilling Engineer","7"],
["Drug Safety Manager","3"],
["Drug Safety Scientist","28"],
["Drug Safety Specialist","22"],
["Drywall Installer / Finisher","44"],
["E-Commerce Analyst","19"],
["E-Commerce Assistant","17"],
["E-Commerce Manager","23"],
["E-Commerce Specialist","159"],
["E-Commerce Web Designer","77"],
["EKG Technician","1000"],
["EMT / Paramedic","2918"],
["ETL Developer","188"],
["Economist","542"],
["Editor","6330"],
["Education Program Manager","15039"],
["Electrical Controls Engineer","332"],
["Electrical Design Engineer","90"],
["Electrical Design Manager","1"],
["Electrical Design Technician","3"],
["Electrical Designer","163"],
["Electrical Engineer (General)","3075"],
["Electrical Engineering Manager","142"],
["Electrical Engineering Technician","664"],
["Electrical Project Engineer","24"],
["Electrical Substation / Relay Repairer","4"],
["Electrical Substation Engineer","6"],
["Electrical Test Engineer","18"],
["Electrician","4256"],
["Electrician's Assistant","73"],
["Electro-Mechanical Engineer","47"],
["Electronic / Electrical Assembler","62"],
["Electronic Design Engineer","28"],
["Electronic Medical Records Specialist","362"],
["Electronic Warfare Engineer","6"],
["Electronic and Electrical Tester","12"],
["Electronics Engineer","614"],
["Electronics Engineering Manager","24"],
["Electronics Field Engineer","9"],
["Electronics Project Engineer","1"],
["Electronics Repair Technician","770"],
["Electronics Technician","687"],
["Electronics Test Engineer","44"],
["Elementary School Teacher","8731"],
["Elementary and Secondary School Administrator","5588"],
["Eligibility Specialist","89"],
["Email Marketing Specialist","500"],
["Embedded Software Engineer","82"],
["Embryologist","66"],
["Emergency Management Director","1130"],
["Emergency Medical Director","284"],
["Emergency Room / Department Technician","1295"],
["Emergency Room Physician Assistant","662"],
["Emergency Room Registered Nurse","3575"],
["Employee Relations Specialist","889"],
["Endocrinology Research Scientist","73"],
["Endoscopy Registered Nurse","538"],
["Endoscopy Technician","575"],
["Energy Analyst / Auditor","306"],
["Energy Efficiency Engineer","22"],
["Energy Efficiency Specialist","47"],
["Energy Engineer","129"],
["Energy Management Engineer","148"],
["Energy Measurement and Verification Engineer","1"],
["Energy Procurement Engineer","3"],
["Energy Sustainability Engineer","11"],
["Engineering Manager (General)","2747"],
["Engineering Program Manager","259"],
["Engineering Project Manager","524"],
["Engineering Technician (General)","1679"],
["Engineering Test Technician","164"],
["English / Language Arts Teacher","1324"],
["Enrollment / Admission Counselor","20414"],
["Enrollment Specialist","2049"],
["Enterprise Account Executive","9"],
["Enterprise Architect","300"],
["Enterprise Sales Manager","2"],
["Entertainment / Recreation Attendant","1751"],
["Environmental Compliance Specialist","114"],
["Environmental Engineer","1806"],
["Environmental Engineering Technician","60"],
["Environmental Field Chemist","195"],
["Environmental Health and Safety (EHS) Coordinator","1400"],
["Environmental Health and Safety (EHS) Director","166"],
["Environmental Health and Safety (EHS) Manager","489"],
["Environmental Planner / Scientist","1304"],
["Environmental Technician","1083"],
["Epidemiologist","1079"],
["Ergonomist","98"],
["Escrow Officer","1"],
["Esthetician","151"],
["Estimator","425"],
["Etcher / Engraver","60"],
["Event Marketing Manager","343"],
["Event Marketing Specialist","505"],
["Event Planner","10855"],
["Event Promotions Marketing Associate","11"],
["Exchange Engineer","164"],
["Executive Assistant","18694"],
["Executive Director","3688"],
["Executive Medical Director","64"],
["Executive Recruiter","56"],
["Exercise Physiologist / Specialist","452"],
["Extruder Machine Operator","1"],
["Facilities Electrical Engineer","262"],
["Facilities Engineer","343"],
["Facilities Engineering Manager","151"],
["Facilities Manager","6799"],
["Facilities Specialist / Coordinator","3605"],
["Family / Behavioral Therapist","1002"],
["Family / General Practitioner","4290"],
["Family / School / General Social Worker","9066"],
["Farm / Nursery / Greenhouse Worker","1244"],
["Farm / Ranch Manager","394"],
["Fashion Designer","886"],
["Field Biologist","31"],
["Field Marketing Manager","11"],
["Field Marketing Specialist","47"],
["Field Operations Manager","97"],
["Field Sales Representative","12"],
["Field Sales Supervisor","2"],
["Field Service Technician","99"],
["File Clerk","1906"],
["Financial Aid Counselor / Specialist","19417"],
["Financial Aid Director","3409"],
["Financial Analyst (General)","5818"],
["Financial Consultant","563"],
["Financial Counselor","862"],
["Financial Examiner","180"],
["Financial Manager (General)","13423"],
["Financial Planner / Investment Consultant","66"],
["Financial Planning Manager","1130"],
["Financial Quantitative Analyst","22"],
["Financial Recruiter","2"],
["Financial Relationship Manager","65"],
["Financial Reporting Accountant","216"],
["Financial Reporting Manager","419"],
["Financial Services Manager","1548"],
["Financial Services Product Manager","36"],
["Financial Services Representative","1868"],
["Finisher / Polisher / Buffer","3"],
["Fire Chief / Marshal","458"],
["Fire Inspector / Investigator","359"],
["Fire Safety Manager","102"],
["Fire Safety Specialist","376"],
["Firefighter","222"],
["Firmware Engineer","46"],
["First Aid Instructor","74"],
["Fish / Game Warden","27"],
["Fish Hatchery Manager / Technician","303"],
["Fitness / Wellness Manager","1044"],
["Flatbed Truck Driver","6"],
["Fleet Maintenance Supervisor","29"],
["Flight Attendant","33"],
["Floor Supervisor","43"],
["Flooring Installer","37"],
["Floral Designer","20"],
["Food / Agricultural Inspector","125"],
["Food / Agricultural Technician","1104"],
["Food / Beverage Buyer","20"],
["Food / Beverage Quality Manager","45"],
["Food Processing Engineer","1"],
["Food Production Worker","42"],
["Food Safety Manager","20"],
["Food Safety Specialist","42"],
["Food Service Team Member","10904"],
["Food and Agricultural Scientist / Technologist","137"],
["Food and Beverage Delivery Driver","50"],
["Forensic Accountant","11"],
["Forensic Chemist","54"],
["Forest / Conservation Technician","383"],
["Forester","230"],
["Forklift / Pallet Jack Operator","61"],
["Fraud Examiner / Analyst","57"],
["Front End Developer","462"],
["Front Office Assistant","378"],
["Fuel Service Attendant","39"],
["Fund / Investment Accountant","338"],
["Fundraising / Development Specialist","7758"],
["Fundraising Manager","35254"],
["Funeral Director / Embalmer","42"],
["Furniture Delivery Driver","6"],
["Furniture Finisher","7"],
["GIS Analyst","1681"],
["Gaming Supervisor","64"],
["Gaming Worker","37"],
["Gas Engineer","1"],
["General ERP Analyst / Consultant","106"],
["General Engineering Technician / Technologist","2906"],
["General Internist","10025"],
["General Manager","11280"],
["General Pediatrician","896"],
["Genetic Counselor","1326"],
["Geneticist","366"],
["Geologist","256"],
["Geophysicist","34"],
["Glazier","43"],
["Global Communications Director","18"],
["Global Communications Manager","124"],
["Golf Course Worker","414"],
["Government / Defense Contracts Manager","118"],
["Graduate Research Fellow","1248"],
["Grants Manager / Administrator","3859"],
["Graphic Designer / Desktop Publisher","10001"],
["Greeter","33"],
["Grinder / Sharpener","39"],
["Grocery Stocker","46"],
["HAZMAT Truck Driver","30"],
["HRIS Analyst / Specialist","529"],
["HVAC Engineer","399"],
["HVAC Mechanic / Installer","6233"],
["Hardware Design Engineer","59"],
["Hardware Engineer","119"],
["Hardware Project Engineer","6"],
["Hardware Test Engineer","7"],
["Hazardous Material Delivery Driver","8"],
["Hazardous Materials Worker","262"],
["Head Cashier","148"],
["Health Educator","2762"],
["Health Information Manager","1565"],
["Health Information Technician / Cancer Registrar","2985"],
["Health Technician / Technologist (Other)","12523"],
["Health and Safety Engineer","838"],
["Health and Wellness Coach","460"],
["Healthcare Account Executive","88"],
["Healthcare Account Manager","159"],
["Healthcare Account Representative","55"],
["Healthcare Administrator","17323"],
["Healthcare Analyst","212"],
["Healthcare Buyer","189"],
["Healthcare Contracts Manager","400"],
["Healthcare Customer Service Representative","764"],
["Healthcare Office Manager","1100"],
["Healthcare Program Manager","815"],
["Healthcare Project Manager","723"],
["Healthcare Recruiter","149"],
["Healthcare Sales Representative","5"],
["Hearing Screener / Technician","107"],
["Heat Treating Technician","22"],
["Heavy Equipment Mechanic","488"],
["Help Desk Technician / Analyst","4143"],
["History / Social Studies Teacher","1935"],
["Histotechnologist / Histotechnician","1895"],
["Home Appliance Repairer","104"],
["Home Health Aide","1261"],
["Home Health Registered Nurse","2154"],
["Hospice Medical Director","7"],
["Hospice Registered Nurse","782"],
["Hospital Medical Director","67"],
["Hospital Pharmacist","513"],
["Hospital Security Officer","959"],
["Hospitalist","2630"],
["Hospitality Front Office Manager","527"],
["Hospitality Operations Supervisor","9"],
["Host / Hostess","689"],
["Hotel & Resort Security Officer","12"],
["Hotel Desk Clerk","2800"],
["Hotel Manager","268"],
["Housekeeping / Environmental Services Supervisor","3370"],
["Human Resources Administrative Assistant","526"],
["Human Resources Analyst","1214"],
["Human Resources Assistant","4040"],
["Human Resources Clerk / Technician","616"],
["Human Resources Consultant","1622"],
["Human Resources Manager","5175"],
["Human Resources Specialist","31118"],
["Hydrologist","110"],
["IT Administrator","962"],
["IT Auditor","641"],
["IT Director","6135"],
["IT Manager","3509"],
["IT Operations / Networking Manager","274"],
["IT Program Manager","225"],
["IT Project Analyst","495"],
["IT Project Manager","5319"],
["IT Specialist / Engineer","3171"],
["Immigration / Customs Inspector","31"],
["Inbound Sales Specialist","1"],
["Incident Analyst / Responder","691"],
["Independent Contractor Truck Driver","295"],
["Industrial / Mechanical Engineering Technician","5284"],
["Industrial Designer","389"],
["Industrial Economic Engineer","35"],
["Industrial Energy Engineer","2"],
["Industrial Engineer","745"],
["Industrial Engineering Manager","119"],
["Industrial Hygiene Specialist","62"],
["Industrial Mechanic","2706"],
["Industrial Plant Engineer","244"],
["Industrial Quality Engineer","27"],
["Industrial-Organizational Psychologist","531"],
["Infectious Disease Scientist","714"],
["Informatica Developer","15"],
["Informatics Pharmacist","97"],
["Information Assurance Engineer / Analyst","171"],
["Information Specialist","170"],
["Infrastructure Architect","88"],
["Infusion Pharmacist","138"],
["Inorganic Chemist","7"],
["Inside Sales Account Executive","22"],
["Inside Sales Account Manager","32"],
["Inside Sales Account Representative","6"],
["Inside Sales Consultant","1"],
["Inside Sales Coordinator","10"],
["Inside Sales Engineer","2"],
["Inside Sales Manager","53"],
["Inside Sales Representative","250"],
["Installation Manager","36"],
["Instrumentation Technician","352"],
["Insulation Worker","24"],
["Insurance Customer Service Representative","18"],
["Insurance Inspector","9"],
["Insurance Medical Director","13"],
["Insurance Sales Agent (General)","573"],
["Insurance Underwriter (General)","60"],
["Integrated Circuit (IC) Design Engineer","24"],
["Intensive / Critical Care Nurse","14060"],
["Intensive Care Registered Nurse","4028"],
["Interior Designer","668"],
["Internal Audit Manager","231"],
["Internal Auditor","2366"],
["Internal Communications Manager","144"],
["International Tax Analyst","9"],
["International Tax Manager","12"],
["Interpreter / Translator","4135"],
["Inventory / Supply Specialist","669"],
["Inventory Analyst","17"],
["Inventory Associate","1759"],
["Inventory Control Manager","51"],
["Investment / Portfolio Analyst","1179"],
["Investment Operations Analyst","71"],
["Investment Underwriter","14"],
["Iron / Steel Worker","11"],
["Isotopes and Radiation Engineer","7"],
["Janitor / Cleaner","23216"],
["Java Architect","53"],
["Java Developer / Engineer","831"],
["JavaScript Developer / Engineer","68"],
["Jeweler","32"],
["Jewelry Sales Associate","14"],
["Judge","183"],
["Junior Accountant","149"],
["Junior Business Analyst","1392"],
["Key Account Manager","41"],
["Key Holder","111"],
["Kitchen Staff","1980"],
["Laboratory Analyst","295"],
["Laboratory Manager","6347"],
["Laboratory Specimen Processor","418"],
["Laboratory Technician (General)","10929"],
["Laborer / Warehouse Worker","3859"],
["Lactation Consultant","247"],
["Land Development Project Manager","3"],
["Landscape Architect","163"],
["Landscaping / Grounds Supervisor","815"],
["Landscaping / Groundskeeping Worker","9145"],
["Laundry Worker","453"],
["Law Clerk","243"],
["Lawn Care / Pesticide Technician","91"],
["Lead Generation Specialist","78"],
["Lead Stocker","1"],
["Lead Teller","26"],
["Lean Manufacturing Engineer","25"],
["Lean Manufacturing Manager","6"],
["Leasing Consultant","144"],
["Legal Researcher","282"],
["Legal Secretary (General)","288"],
["Legal Support Specialist","130"],
["Librarian","24443"],
["Library Assistant / Technician","10778"],
["Licensed Practical / Vocational Nurse","18979"],
["Life / Health Insurance Sales Agent","54"],
["Lifeguard","2030"],
["Light Truck Delivery Driver","1469"],
["Litigation Legal Secretary","8"],
["Loan Administrator / Manager","27"],
["Loan Documentation Specialist","18"],
["Loan Officer (General)","461"],
["Loan Processor (General)","631"],
["Loan Underwriter","14"],
["Locksmith","957"],
["Logging Worker / Supervisor","27"],
["Logistician","95"],
["Logistics / Supply Chain Account Manager","13"],
["Logistics / Supply Chain Account Representative","9"],
["Logistics Analyst","8"],
["Logistics Coordinator","10"],
["Logistics Director","20"],
["Logistics Management Specialist","5"],
["Logistics Manager","89"],
["Logistics Operations Supervisor","135"],
["Logistics Specialist","131"],
["Logistics Supervisor","47"],
["Long-Term Care Pharmacist","122"],
["Loss Control Consultant","8"],
["Loss Prevention / Asset Protection Specialist","1592"],
["MRI / CT Technician / Technologist","2957"],
["Machine Set Up Technician","21"],
["Machine Shop Supervisor","61"],
["Machine Tool Engineer","9"],
["Machining Process Engineer","15"],
["Machinist","559"],
["Maid / Housekeeping Staff","6237"],
["Mainframe Developer","23"],
["Maintenance Group Leader","25"],
["Maintenance Helper / Assistant","1013"],
["Maintenance Manager","407"],
["Maintenance Planner","55"],
["Maintenance Service Manager","377"],
["Maintenance Service Supervisor","130"],
["Maintenance Superintendent","15"],
["Maintenance Supervisor","4043"],
["Makeup Artist","66"],
["Manager of Clinical Data Management","38"],
["Manager of Health Information Management","239"],
["Manager of Product Management","9"],
["Managing Director (General)","1088"],
["Manicurist / Pedicurist","113"],
["Manufacturing / Production Technician","1004"],
["Manufacturing Assembly Engineer","7"],
["Manufacturing Automation Engineer","3"],
["Manufacturing Chemist","17"],
["Manufacturing Director","44"],
["Manufacturing Engineer","364"],
["Manufacturing Engineering Manager","1"],
["Manufacturing Machine Operator","1219"],
["Manufacturing Manager","80"],
["Manufacturing Process Engineer","31"],
["Manufacturing Production Supervisor","133"],
["Manufacturing Project Engineer","20"],
["Manufacturing Project Manager","22"],
["Manufacturing Quality Manager","70"],
["Manufacturing Test Engineer","26"],
["Marine Engineer / Architect","133"],
["Market Research Analyst","806"],
["Marketing & Sales Representative","59"],
["Marketing Account Executive","74"],
["Marketing Analyst","183"],
["Marketing Analytics Manager","101"],
["Marketing Analytics Specialist","58"],
["Marketing Assistant / Associate","2037"],
["Marketing Associate","190"],
["Marketing Automation Analyst","96"],
["Marketing Automation Manager","74"],
["Marketing Automation Specialist","36"],
["Marketing Campaign Analyst","38"],
["Marketing Campaigns Manager","157"],
["Marketing Communications Director","1492"],
["Marketing Communications Manager","875"],
["Marketing Communications Specialist","492"],
["Marketing Consultant","46"],
["Marketing Director","2566"],
["Marketing Manager (General)","4361"],
["Marketing Operations Analyst","15"],
["Marketing Operations Manager","412"],
["Marketing Operations Specialist","30"],
["Marketing Specialist","3520"],
["Marketing Strategist","289"],
["Massage Therapist","675"],
["Materials Analyst","1"],
["Materials Development Engineer","5"],
["Materials Engineer","143"],
["Materials Laboratory Technician","108"],
["Materials Manager","79"],
["Materials Planner","24"],
["Materials Research Engineer","29"],
["Materials Tester","1"],
["Math Teacher","1415"],
["Mathematician","73"],
["Meat and Seafood Processor / Packager","35"],
["Mechanical / Electrical Drafter","372"],
["Mechanical Design Engineer","562"],
["Mechanical Engineer (General)","4018"],
["Mechanical Engineer Surveyor","37"],
["Mechanical Engineering Manager","273"],
["Mechanical Project Engineer","19"],
["Mechanical Reliability Engineer","41"],
["Mechanical Systems Engineer","238"],
["Mechanical Testing Engineer","11"],
["Mechatronics Engineer","53"],
["Media Advertising Sales Representative","9"],
["Media Planner / Buyer","1793"],
["Medical / Clinical Social Worker","2944"],
["Medical Assembler","11"],
["Medical Assistant","24042"],
["Medical Biller","958"],
["Medical Billing Representative","642"],
["Medical Claims Examiner","136"],
["Medical Claims Processor / Representative","11"],
["Medical Coder","3853"],
["Medical Device Sales Representative","17"],
["Medical Director (General)","1339"],
["Medical Director of Allergy and Immunology","1"],
["Medical Director of Anatomic / Clinical Pathology ","11"],
["Medical Director of Anesthesiology","2"],
["Medical Director of Cardiovascular Disease","18"],
["Medical Director of Critical Care Medicine","31"],
["Medical Director of Endocrinology, Diabetes, and Metabolism","28"],
["Medical Director of Family Medicine / General Practice","36"],
["Medical Director of Gastroenterology","21"],
["Medical Director of Geriatric Medicine","11"],
["Medical Director of Hematology / Oncology","65"],
["Medical Director of Infectious Disease","16"],
["Medical Director of Neonatal / Perinatal Medicine","2"],
["Medical Director of Nephrology","1"],
["Medical Director of Neurology","2"],
["Medical Director of Obstetrics and Gynecology","18"],
["Medical Director of Pain Medicine and Pain Management","14"],
["Medical Director of Pediatrics","51"],
["Medical Director of Physical Medicine and Rehabilitation","4"],
["Medical Director of Preventive Medicine","48"],
["Medical Director of Psychiatry","55"],
["Medical Director of Radiology","2"],
["Medical Director of Rheumatology","1"],
["Medical Director of Surgery","121"],
["Medical Director of Vascular Surgery","13"],
["Medical Laboratory Scientist","1876"],
["Medical Laboratory Technician","4827"],
["Medical Laboratory Technologist","1256"],
["Medical Office Manager","226"],
["Medical Practice Manager","865"],
["Medical Records / Coding Supervisor","972"],
["Medical Records Clerk / Technician","2557"],
["Medical Research Scientist","5116"],
["Medical Research Specialist","3331"],
["Medical Sales Account Manager","6"],
["Medical Sales Representative","20"],
["Medical Science Liaison","16"],
["Medical Secretary","12704"],
["Medical Staff Director","59"],
["Medical Surgery Registered Nurse","4896"],
["Medical Technologist","3002"],
["Medical Technologist Supervisor","27"],
["Medical Transcriptionist","571"],
["Medication Aide / Technician","724"],
["Membership Sales Manager","19"],
["Membership Sales Representative","120"],
["Mental Health / Behavioral Counselor","14179"],
["Mental Health / Psychiatric Technician","1046"],
["Mental Health Assistant","656"],
["Mental Health Educator","1035"],
["Merchandise Coordinator","21"],
["Merchandise Handler","61"],
["Merchandise Manager","29"],
["Merchandise Presentation Specialist","5"],
["Merchandiser","1308"],
["Merchandising Lead","3"],
["Merchandising Manager","51"],
["Merchandising Specialist","13"],
["Metallurgical Engineer","3"],
["Meteorologist","181"],
["Meter Reader","102"],
["Microbiologist","1258"],
["Microbiology Laboratory Assistant","3275"],
["Microbiology Medical Technologist","959"],
["Mid-Market Account Executive","2"],
["Middle / High School Teacher","1758"],
["Middleware Administrator","55"],
["Midwife / Nurse Midwife","523"],
["Millwright","61"],
["Miner / Mining Worker","48"],
["Mining Engineer","20"],
["Mixing Machine Operator","1"],
["Mobile Developer / Engineer","414"],
["Molding / Casting Worker","61"],
["Molding Process Engineer","3"],
["Molecular Biologist","261"],
["Mortgage Loan Officer","214"],
["Mortgage Manager","198"],
["Motor Vehicle Operator / Transporter","289"],
["Multimedia Designer / Animator","744"],
["Municipal / License / Court Clerk","398"],
["Music Director","1577"],
["Music Teacher","1414"],
["Musician / Singer","1006"],
["MySQL Database Administrator","22"],
["Mystery Shopper","12"],
["Nanny / Babysitter","3925"],
["Natural Science Research Director","8"],
["Natural Sciences Research Manager","2163"],
["Network Administrator","1834"],
["Network Analyst / Specialist","1521"],
["Network Engineer / Architect","5087"],
["Network Reliability Engineer","3"],
["Network Support Technician","1218"],
["Neural Engineer","1"],
["Neurodiagnostic Technician / Technologist","1403"],
["Neurologist","1811"],
["Night Auditor","139"],
["Night Stocker","22"],
["Non-Destructive Testing Specialist","293"],
["Nuclear Engineer","102"],
["Nuclear Medicine Technologist","531"],
["Nuclear Pharmacist","25"],
["Nuclear Project Engineer","5"],
["Nuclear Safety Engineer","2"],
["Nurse Anesthetist","1770"],
["Nurse Manager","6779"],
["Nurse Practitioner","13789"],
["Nurse Supervisor","1993"],
["Nursery / Greenhouse Manager","123"],
["Nursing Assistant","21803"],
["Nursing Home / Home Health Administrator","94"],
["Nursing Instructor / Professor","44509"],
["Nutrition / Dietetic Technician","1471"],
["OB / GYN Registered Nurse","3504"],
["Obstetrician / Gynecologist","2681"],
["Occupational Health and Safety (OHS) Director","8"],
["Occupational Health and Safety (OHS) Manager","197"],
["Occupational Health and Safety (OHS) Specialist","643"],
["Occupational Therapist","5310"],
["Occupational Therapy Aide","1084"],
["Occupational Therapy Assistant","3076"],
["Office / Administrative Assistant","110413"],
["Office Automation Clerk","312"],
["Office Manager (General)","8518"],
["Office Technician / Typist","1507"],
["Oil / Gas Field Service Technician","34"],
["Oilfield / Rig Worker","11"],
["Oncology Pharmacist","1442"],
["Oncology Registered Nurse","3276"],
["Oncology Research Scientist","1992"],
["Oncology Research Specialist","878"],
["Operating Engineer / Heavy Equipment Operator","806"],
["Operating Room Registered Nurse","3962"],
["Operations Analyst (General)","1114"],
["Operations Coordinator","417"],
["Operations Engineering Manager","65"],
["Operations Industrial Engineer","58"],
["Operations Manager","7423"],
["Operations Project Manager","80"],
["Operations Research Analyst","64"],
["Operations Supervisor","1915"],
["Operations and Maintenance Specialist","97"],
["Ophthalmic Technician","1810"],
["Optical / Laser Engineer","163"],
["Optician","270"],
["Opto-Mechanical Engineer","61"],
["Optometrist","306"],
["Oracle Consultant / Analyst","29"],
["Oracle Database Administrator","720"],
["Oracle Developer","185"],
["Order Processor / Order Entry Clerk","258"],
["Organic Chemist","844"],
["Orthopedic Biomedical Engineer","3"],
["Orthopedics Physician Assistant","307"],
["Orthoptist","101"],
["Orthotist / Prosthetist","124"],
["Outside Sales Account Executive","31"],
["Outside Sales Account Manager","34"],
["Outside Sales Account Representative","5"],
["Outside Sales Consultant","6"],
["Outside Sales Coordinator","4"],
["Outside Sales Engineer","1"],
["Outside Sales Representative","300"],
["Over-the-Road (OTR) Truck Driver","34"],
["Owner / Operator Truck Driver","21"],
["PACU Registered Nurse","2831"],
["PCB Layout and Design Engineer","4"],
["PCU / Stepdown Registered Nurse","849"],
["PHP Developer","206"],
["PL / SQL Developer","22"],
["Packager","88"],
["Packaging Designer","4"],
["Packaging Industrial Engineer","18"],
["Packaging Machine Operator","38"],
["Painter","2045"],
["Paralegal / Legal Assistant","2121"],
["Parking Enforcement Officer","782"],
["Parts Clerk","2"],
["Parts Counter Representative","4"],
["Parts Sales Representative","50"],
["Parts Specialist","10"],
["Pathology Laboratory Technician","1196"],
["Pathology Technologist","92"],
["Patient Advocate / Navigator","828"],
["Patient Safety Director","607"],
["Patient Safety Manager","39"],
["Patient Safety Specialist","237"],
["Patient Transporter","1730"],
["Pay Per Click Specialist","23"],
["Payroll Accountant","1145"],
["Payroll Administrator","205"],
["Payroll Analyst","352"],
["Payroll Clerk","1341"],
["Payroll Manager","1003"],
["Payroll Specialist (General)","2051"],
["Pediatrics Nurse Practitioner","2155"],
["Pediatrics Registered Nurse","1506"],
["Peoplesoft Developer / Administrator","306"],
["Performance Engineer","66"],
["Perl Developer","14"],
["Personal Assistant","398"],
["Personal Banker (General)","150"],
["Personal Financial Advisor (General)","3451"],
["Personal Trainer / Fitness Instructor","4924"],
["Pest Control Technician","234"],
["Pet Care Worker / Manager","2340"],
["Pet Trainer","27"],
["Petroleum Engineer","114"],
["Pharmaceutical Account Executive","12"],
["Pharmaceutical Manufacturing Process Engineer","1"],
["Pharmaceutical Sales Manager","1"],
["Pharmaceutical Sales Representative","9"],
["Pharmacist (General)","2316"],
["Pharmacology Research Scientist","447"],
["Pharmacy Aide","495"],
["Pharmacy Delivery Driver","8"],
["Pharmacy Director","484"],
["Pharmacy Practice Resident","317"],
["Pharmacy Technician","7595"],
["Phlebotomist","2657"],
["Photo Laboratory Technician","12"],
["Photographer","2121"],
["Physical / Geoscience Technician","211"],
["Physical Chemist","39"],
["Physical Education Teacher","348"],
["Physical Scientist","53"],
["Physical Therapist","6625"],
["Physical Therapy Aide","314"],
["Physical Therapy Assistant","4850"],
["Physician Assistant","10446"],
["Physician Assistant / Nurse Practitioner","4954"],
["Physician Practice Manager","24"],
["Physician Recruiter","98"],
["Physician, Other","13451"],
["Physicist","2140"],
["Physiologist","207"],
["Pilot","200"],
["Pilot Instructor","758"],
["Pipe Fitter","734"],
["Pipeline Worker / Operator","7"],
["Planning Director","34"],
["Plant Controller","6"],
["Plant Operator","916"],
["Plasma Processor","9"],
["Plasterer / Stucco Mason","81"],
["Plastics Engineer","4"],
["Plating Machine Operator","4"],
["Plumber","2346"],
["Plumbing Engineer","66"],
["Police Chief / Sergeant","2464"],
["Police Officer","11821"],
["Policy Analyst","1873"],
["Polymer Chemist","9"],
["Postal Service / Mail Room Worker","2085"],
["Power Distributor / Plant Operator","196"],
["Power Electronics Engineer","71"],
["Pre - Press Technician","369"],
["Pre-Construction Manager","3"],
["Pre-Sales Engineer","3"],
["Preschool / Childcare Teacher","11690"],
["Press / Press Brake Operator","156"],
["Preventive Medicine Physician","71"],
["Pricing Analyst","12"],
["Pricing Associate","7"],
["Pricing Coordinator","5"],
["Pricing Manager","3"],
["Primary Care Nurse Practitioner","2596"],
["Print Bindery / Finishing Worker","218"],
["Printer / Copier / Scanner Operator","362"],
["Printing Press Operator","208"],
["Probation Officer / Correctional Treatment Specialist","148"],
["Process Control Engineer","75"],
["Process Development Engineer","43"],
["Process Engineer","263"],
["Process Industrial Engineer","101"],
["Process Manager","76"],
["Process Quality Engineer","6"],
["Procurement / Sourcing Manager","930"],
["Procurement / Sourcing Specialist","1064"],
["Procurement Analyst","375"],
["Producer","2186"],
["Product Brand Manager","13"],
["Product Demonstrator","168"],
["Product Design Engineer","20"],
["Product Designer","127"],
["Product Development Engineer","28"],
["Product Development Manager","31"],
["Product Engineering Manager","34"],
["Product Line Manager","7"],
["Product Manager","422"],
["Product Marketing Analyst","26"],
["Product Marketing Director","378"],
["Product Marketing Manager","516"],
["Product Marketing Specialist","38"],
["Product Quality Engineer","2"],
["Product Support Engineer","3"],
["Production Engineer","79"],
["Production Machine Operator","73"],
["Production Planner","14"],
["Production Plant Foreman","18"],
["Production Plant Manager","1989"],
["Production Plant Supervisor","150"],
["Production Process Supervisor","4"],
["Production Shift Supervisor","39"],
["Production Supervisor","2129"],
["Production Worker","3492"],
["Program Analyst","1460"],
["Program Coordinator","6505"],
["Program Coordinator, Higher Education","8713"],
["Program Director, Higher Education","15639"],
["Program Manager (General)","265"],
["Program Officer","502"],
["Programmable Logic Controller (PLC) Programmer","6"],
["Programmable Logic Controller (PLC) Technician","123"],
["Programmer / Analyst","10543"],
["Project / Program Administrative Assistant","17009"],
["Project Accountant","113"],
["Project Controls Manager","47"],
["Project Coordinator","8707"],
["Project Management Analyst","122"],
["Project Manager (General)","13698"],
["Proofreader","115"],
["Property Appraiser / Assessor","112"],
["Property Manager","2416"],
["Provost","2814"],
["Psychiatric Registered Nurse","1607"],
["Psychiatrist","3323"],
["Psychiatry Nurse Practitioner","1135"],
["Psychologist","8361"],
["Public / Community Health Nurse","731"],
["Public Accountant","36"],
["Public Affairs Director","368"],
["Public Affairs Manager","89"],
["Public Health Officer","68"],
["Public Relations / Communications Specialist","23024"],
["Public Relations Director","1093"],
["Public Relations Manager","480"],
["Public Relations Officer","238"],
["Public Service Administrator","28"],
["Pump Worker / Operator","67"],
["Purchasing Agent","540"],
["Purchasing Assistant","1753"],
["Purchasing Manager","380"],
["Python Developer","73"],
["Quality Assurance Auditor","29"],
["Quality Assurance Manager","380"],
["Quality Assurance Specialist","457"],
["Quality Assurance Supervisor","61"],
["Quality Control Analyst","1830"],
["Quality Control Chemist","4"],
["Quality Control Laboratory Technician","31"],
["Quality Control Manager","65"],
["Quality Control Technician","84"],
["Quality Engineering Manager","32"],
["Quality Inspector","1070"],
["Quality Manager (General)","473"],
["Quality Technician","37"],
["Quality Validation Engineer","53"],
["RF Engineer","123"],
["Radiation Therapist","1400"],
["Radio / Television Announcer","506"],
["Radio Technician","46"],
["Radiologic Technician / Technologist","7330"],
["Railroad Conductor","21"],
["Railroad Service Worker","50"],
["Reading Teacher","722"],
["Real Estate / Property Accountant","51"],
["Real Estate Agent","1326"],
["Real Estate Legal Secretary","2"],
["Realty Specialist","1"],
["Receptionist","7753"],
["Recreation / Activities Worker","7934"],
["Recreation Manager","154"],
["Recruiter (General)","5907"],
["Recruiting Assistant","963"],
["Recruiting Manager","291"],
["Recycling / Sanitation Worker","151"],
["Recycling Coordinator","135"],
["Refrigeration Technician","232"],
["Regional / Area Controller","12"],
["Regional Planner","30"],
["Regional Sales Assistant","4"],
["Regional Truck Driver","12"],
["Registered Nurse","68250"],
["Registrar","6653"],
["Registrar / Patient Service Representative","13663"],
["Regulatory Affairs Specialist","1169"],
["Reliability Engineer","7"],
["Renewable Energy Engineer","14"],
["Rental Clerk","18"],
["Repair / Service Technician","8097"],
["Reporter","1719"],
["Research & Development Engineer","955"],
["Research Analyst","3092"],
["Research Assistant","14364"],
["Research Associate","45973"],
["Research Laboratory Technician","1609"],
["Research Medical Technologist","1376"],
["Research Scientist","7535"],
["Research Technician","3826"],
["Research and Development Chemist","148"],
["Research and Development Director","93"],
["Research and Development Manager","13"],
["Reservation / Ticket Agent","149"],
["Reservoir Engineer","18"],
["Residential Assistant / Advisor","9496"],
["Residential Community Manager","709"],
["Residential Construction Superintendent","3"],
["Residential Services Administrator","6077"],
["Respiratory Therapist","3861"],
["Restaurant / Food Service Manager","6131"],
["Restaurant / Food Service Supervisor","5793"],
["Restaurant Cashier","4"],
["Restaurant Delivery Driver","115"],
["Retail Apparel Associate","19"],
["Retail Associate Manager","19"],
["Retail Beauty Consultant","12"],
["Retail Customer Service Manager","10"],
["Retail Event Staff","469"],
["Retail Merchandiser","72"],
["Retail Operations Supervisor","138"],
["Retail Pharmacist","1036"],
["Retail Pharmacy Manager","521"],
["Retail Pricing Coordinator","80"],
["Retail Project Merchandiser","5"],
["Retail Reset Merchandiser","1"],
["Retail Sales Associate (General)","5765"],
["Retail Sales Consultant","53"],
["Retail Sales Representative","132"],
["Retail Sales Supervisor","110"],
["Retail Security Officer","10"],
["Retail Service Manager","5"],
["Retail Stocker","4"],
["Retail Store Clerk","282"],
["Retail Store Manager","4994"],
["Retail Store Shift Supervisor","78"],
["Retail Store Supervisor","599"],
["Revenue Accountant","72"],
["Revenue Manager","434"],
["Rigger","39"],
["Risk Analyst","261"],
["Risk Consultant","102"],
["Risk Manager","400"],
["Robotics Engineer","332"],
["Robotics Technician","86"],
["Roofing / Siding Worker","242"],
["Route Sales Delivery Driver","27"],
["Route Sales Manager","2"],
["Route Sales Representative","9"],
["Ruby On Rails Developer","85"],
["SAP Analyst / Admin","206"],
["SAP Architect / Analyst","55"],
["SAP Developer","17"],
["SAP Manager","89"],
["SAS Programmer","875"],
["SQL Developer","223"],
["SQL Server Database Administrator","118"],
["SQL Server Developer","36"],
["Safety Compliance Manager","183"],
["Safety Coordinator","152"],
["Safety Director","30"],
["Safety Manager","160"],
["Safety Specialist","1352"],
["Sailor / Deckhand / Marine Oiler","266"],
["Sales Advisor","27"],
["Sales Assistant","307"],
["Sales Consultant","97"],
["Sales Coordinator","191"],
["Sales Delivery Driver","460"],
["Sales Engineer","113"],
["Sales Engineering Manager","35"],
["Sales Event Specialist","343"],
["Sales Lead","12"],
["Sales Manager","1163"],
["Sales Operations Manager","92"],
["Sales Program Manager","13"],
["Sales Recruiter","122"],
["Sales Representative","4495"],
["Sales Supervisor","895"],
["Sales Support Assistant","118"],
["Sales Support Associate","23"],
["Sales Support Engineer","2"],
["Sales Support Representative","5"],
["Sales Support Specialist","42"],
["Sales Trainer","59"],
["Sales and Marketing Director","87"],
["Sales and Marketing Manager","28"],
["Sales and Marketing Specialist","315"],
["Salesforce / CRM Developer","226"],
["Salesforce Administrator","566"],
["Salesforce Developer","15"],
["Salon / Spa Manager","74"],
["Sanitation Specialist","20"],
["Satellite Technician","184"],
["Saw Operator","11"],
["Scheduler / Operations Coordinator","6496"],
["School Athletic Director","44"],
["School Nurse","284"],
["School Principal","842"],
["Science Teacher","1956"],
["Search Engine Marketing Manager","20"],
["Search Engine Marketing Specialist","79"],
["Search Engine Optimization Manager","21"],
["Search Engine Optimization Specialist","451"],
["Seasonal Cashier","148"],
["Secretary","8477"],
["Securities / Commodities Trader","45"],
["Security / Defense Intelligence Analyst","264"],
["Security Driver","159"],
["Security Manager","302"],
["Security Officer","157"],
["Security Supervisor","224"],
["Self-Enrichment Teacher","3550"],
["Senior .NET Developer / Engineer","88"],
["Senior Accountant","2626"],
["Senior Business Analyst","3124"],
["Senior Buyer","711"],
["Senior Compensation / Benefits Analyst","445"],
["Senior Credit Analyst","9"],
["Senior Data Analyst","470"],
["Senior Data Scientist","58"],
["Senior Executive Assistant","1146"],
["Senior Financial Analyst","1444"],
["Senior Human Resources Consultant","505"],
["Senior Insurance Underwriter","2"],
["Senior Java Developer / Engineer","374"],
["Senior Loan Processor","2"],
["Senior Office / Administrative Assistant","9784"],
["Senior Operations Analyst","66"],
["Senior Payroll Specialist","215"],
["Senior Program Manager","1"],
["Senior Project Manager","1713"],
["Senior Recruiter","185"],
["Senior Software Developer / Engineer","2508"],
["Senior Tax Manager","79"],
["Senior Web Developer","955"],
["Server Administrator","743"],
["Service / Sales Engineer","2"],
["Set / Exhibit Designer","131"],
["Sewing Machine Operator","17"],
["SharePoint Developer","132"],
["Sharepoint Administrator","161"],
["Sheet Metal Fabricator / Mechanic","257"],
["Sheriff","117"],
["Ship / Boat Captain","216"],
["Shipping / Receiving Clerk","1392"],
["Signal Processing Engineer","182"],
["Site Safety Manager","8"],
["Site Safety Specialist","12"],
["Six Sigma Quality Engineer","60"],
["Sleep Laboratory Technician","51"],
["Sleep Laboratory Technologist","24"],
["Small Engine Mechanic","41"],
["Social / Human Service Assistant","4592"],
["Social / Human Services Manager","2995"],
["Social Media Strategist / Specialist","3072"],
["Social Science Researcher","13804"],
["Software Account Executive","12"],
["Software Architect","407"],
["Software Developer / Engineer","17479"],
["Software Development / Engineering Manager","1145"],
["Software Product Manager","187"],
["Software QA Analyst","767"],
["Software QA Engineer / Tester","1471"],
["Software QA Lead","154"],
["Software Sales Representative","1"],
["Software as a Service (SaaS) Sales Engineer","1"],
["Software as a Service (Saas) Sales Manager","2"],
["Soil / Plant Scientist","660"],
["Solar Engineer","6"],
["Solar Installer","21"],
["Solar Sales Representative","7"],
["Solutions Engineer","90"],
["Sound Engineering Technician","1472"],
["Special Education Teacher","9467"],
["Speech Language Pathologist","4626"],
["Speech Language Pathology Assistant","58"],
["Staffing Assistant","124"],
["Staffing Manager","2052"],
["Staffing Specialist","2446"],
["Stage Manager","203"],
["Stationary Engineer / Boiler Operator","1052"],
["Statistician","2933"],
["Sterile Processing Technician","3984"],
["Stock Associate","6"],
["Stocker","1199"],
["Storage Engineer","297"],
["Store Lead","1"],
["Store Sales Manager","13"],
["Strategic Marketing Analyst","53"],
["Structural Materials Engineer","3"],
["Student Affairs Administrator","8537"],
["Student Support Administrator","447"],
["Student Truck Driver","77"],
["Substance Abuse Counselor","448"],
["Substitute Teacher","947"],
["Superintendent (Education)","440"],
["Supervisor of Health Information Management","101"],
["Supplier Quality Engineer","44"],
["Supply Chain Analyst","333"],
["Supply Chain Director","122"],
["Supply Chain Manager","902"],
["Supply Chain Project Manager","31"],
["Supply Chain Specialist","49"],
["Supply Management Specialist","115"],
["Supply Planner","1"],
["Support Engineer","338"],
["Surgeon","3989"],
["Surgical Physician Assistant","1038"],
["Surgical Technician / Technologist","6541"],
["Surveillance Officer / Investigator","1388"],
["Survey Researcher","3695"],
["Surveying / Mapping Technician","216"],
["Surveyor","144"],
["Sustainability Specialist","381"],
["Switchboard / Telephone Operator","1509"],
["Systems Administrator","9506"],
["Systems Analyst","6920"],
["Systems Architect","337"],
["Systems Engineer","5377"],
["Systems Integration Engineer / Specialist","699"],
["Systems Physiologist","2"],
["Systems Support Specialist","5975"],
["Systems Validation Engineer","7"],
["Tailor / Seamstress","71"],
["Tanker Truck Driver","2"],
["Tattoo Artist","4"],
["Tax Accountant","221"],
["Tax Analyst","100"],
["Tax Manager (General)","152"],
["Tax Preparer","38"],
["Tax Senior","10"],
["Tax Specialist","126"],
["Taxonomist","3"],
["Teacher Assistant","14464"],
["Technical Account Manager","29"],
["Technical Consultant / Analyst","3998"],
["Technical Customer Service Representative","14"],
["Technical Manager / Director","781"],
["Technical Manufacturing Manager","3"],
["Technical Product Manager","2"],
["Technical Program Manager","144"],
["Technical Project Manager","822"],
["Technical Recruiter","151"],
["Technical Sales Engineer","4"],
["Technical Sales Representative","38"],
["Technical Sales Specialist","2"],
["Technical Support Engineer / Analyst","5331"],
["Technical Support Manager / Supervisor","667"],
["Technical Trainer","374"],
["Technical Writer","1552"],
["Technology Account Executive","10"],
["Technology Brand Ambassador","2"],
["Telecommunications Account Manager","13"],
["Telecommunications Field Technician","272"],
["Telecommunications Network Technician","291"],
["Telecommunications Specialist / Engineer","829"],
["Telemarketer","166"],
["Telemetry Registered Nurse","983"],
["Telemetry Technician","743"],
["Telesales Representative","4"],
["Television / Satellite Television Installer","37"],
["Teller (General)","610"],
["Territory / Regional Account Executive","17"],
["Territory / Regional Account Manager","29"],
["Territory / Regional Director of Sales","1157"],
["Territory / Regional Sales Engineer","2"],
["Territory / Regional Sales Manager","416"],
["Territory / Regional Sales Representative","37"],
["Test Validation Engineer","2"],
["Thermal Engineer","12"],
["Tile / Granite Worker","23"],
["Tire Changer / Technician","131"],
["Title Clerk (General)","214"],
["Title Examiner","2"],
["Tool and Die Maker","27"],
["Tow Truck Driver","17"],
["Tower Climber / Technician","1"],
["Tractor-Trailer Truck Driver (General)","1577"],
["Trade Marketing Analyst","4"],
["Traffic Analyst","7"],
["Training Consultant","187"],
["Training and Development Manager","1679"],
["Training and Development Specialist","7651"],
["Transportation Analyst","4"],
["Transportation Engineer","96"],
["Transportation Inspector","26"],
["Transportation Maintenance Worker","70"],
["Transportation Manager","677"],
["Transportation Planner","90"],
["Transportation Safety Manager","5"],
["Transportation Safety Specialist","31"],
["Transportation Security Officer","50"],
["Transportation Specialist","111"],
["Transportation Supervisor","326"],
["Travel / Tour Guide","1195"],
["Travel Agent","153"],
["Treasury Analyst","971"],
["Tree Climber / Trimmer","78"],
["Tutor","25408"],
["Ultrasound Technologist / Sonographer","4631"],
["Umpire / Referee","630"],
["Underwriting Assistant","270"],
["Unix Administrator / Engineer","1847"],
["Upholsterer","28"],
["Urban Planner","186"],
["Urologist","818"],
["User Experience (UX) Designer","497"],
["User Experience (UX) Developer","100"],
["User Experience (UX) Researcher","54"],
["User Interface (UI) Designer","53"],
["User Interface (UI) Developer","313"],
["User Interface / User Experience (UI / UX) Designer","2968"],
["User Interface / User Experience (UI / UX) Developer","9"],
["User Interface / User Experience (UI / UX) Manager","21"],
["Utilities & Power Distribution Engineer","240"],
["Utility Line Locator / Technician","84"],
["VMware Engineer / Administrator","53"],
["VP / Director of Finance","1871"],
["Valet / Parking Lot Attendant","919"],
["Validation Engineer","42"],
["Validation Specialist","13"],
["Van / Taxi / Shuttle Driver","1324"],
["Vb.Net Developer","28"],
["Vehicle Service Attendant","10"],
["Vendor Manager","21"],
["Veterinarian","1158"],
["Veterinary Assistant","1343"],
["Veterinary Practice Manager","5"],
["Veterinary Technician / Technologist","4670"],
["Vice President (General)","1679"],
["Vice President of Communications","948"],
["Vice President of Engineering","12"],
["Vice President of Marketing","395"],
["Vice President of Operations","327"],
["Video Editor","172"],
["Video Game Designer","52"],
["Videographer","1215"],
["Vocational Education Instructor","22686"],
["Vocational Rehabilitation Counselor","433"],
["Vulnerability Analyst / Penetration Tester","521"],
["Waiter / Waitress","2238"],
["Warehouse / Distribution Supervisor","334"],
["Warehouse Manager","246"],
["Waste Truck Driver","5"],
["Water / Wastewater Engineer","78"],
["Water Resource Specialist","20"],
["Water Treatment Specialist / Waste Water Operator","176"],
["Weatherization Installer","10"],
["Web Content Producer","475"],
["Web Design Manager","21"],
["Web Designer","2263"],
["Web Developer","7860"],
["Webmaster / Administrator","2836"],
["Welder / Solderer","421"],
["Welding Engineer","3"],
["Welding Process Engineer","4"],
["Wildlife Biologist","1447"],
["Wind Energy Engineer","3"],
["Wind Turbine Technician","93"],
["Windows Administrator","505"],
["Windows Engineer","191"],
["Writer","3983"],
["Youth Counselor / Worker","730"],
["iOS Developer / Engineer","42"],
["na","310365"]
]
